<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AuthToken"
     targetNamespace="http://xmlns.oracle.com/SOACmxIntApp/GraphAPIPrj/AuthToken"
     xmlns:tns="http://xmlns.oracle.com/SOACmxIntApp/GraphAPIPrj/AuthToken"
     xmlns:inp1="http://www.spsolutions.com.mx/demo/graphapi/schemas/token"
     xmlns:inp2="http://xmlns.oracle.com/SOACmxIntApp/GraphAPIPrj/AuthToken"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="AuthToken">
        <plnk:role name="AuthTokenProvider" portType="tns:AuthToken_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.spsolutions.com.mx/demo/graphapi/schemas/token" schemaLocation="../Schemas/AuthToken.xsd"/>
        </xsd:schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.oracle.com/SOACmxIntApp/GraphAPIPrj/AuthToken"
             elementFormDefault="qualified">
            <element name="empty">
                <complexType/>
            </element>
        </schema>
    </wsdl:types>
    <wsdl:message name="ReqTokenPass_inputMessage">
        <wsdl:part name="request" element="inp1:authTokenRequest"/>
    </wsdl:message>
    <wsdl:message name="Rest_EmptyMessage">
        <wsdl:part name="Empty" element="tns:empty"/>
    </wsdl:message>
    <wsdl:portType name="AuthToken_ptt">
        <wsdl:operation name="ReqTokenPass">
            <wsdl:input message="tns:ReqTokenPass_inputMessage"/>
            <wsdl:output message="tns:Rest_EmptyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
